version: '3.4'

services:
  smakownia.identity.api:
    image: ${DOCKER_REGISTRY-}smakowniaidentityapi
    build:
      context: .
      dockerfile: src/Smakownia.Identity.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    networks:
      - default
      - smakownia
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=aruzo
      - POSTGRES_PASSWORD=yourStrong(!)Password

volumes:
  postgres-data:

networks:
  smakownia:
    name: smakownia